sarabande/models/user.py
from flask_login import UserMixin

from sarabande import db, bcrypt


class User(db.Model, UserMixin):
    __tablename__ = 'users'

    username = db.Column(db.String, unique=True, nullable=False, index=True)
    user_type = db.Column(db.String, nullable=False, default='commenter')
    password_hash = db.Column(db.String, nullable=False)
    USER_LEVELS = ['admin', 'user', 'commenter']

    def __init__(self, *args, **kwargs):
        if 'password' in kwargs:
            kwargs['password_hash'] = bcrypt.generate_password_hash(
                kwargs['password'])
            del kwargs['password']
        super(User, self).__init__(*args, **kwargs)

    def __repr__(self):
        return '<User {username}>'.format(username=self.username)

    def set_password(self, password):
        self.password_hash = bcrypt.generate_password_hash(password)

    def valid_password(self, password):
        return bcrypt.check_password_hash(self.password_hash, password)

    def authorized_for(self, user_type):
        for level in self.USER_LEVELS:
            if level == self.user_type:
                return True
            if level == user_type:
                return False

    @property
    def is_admin(self):
        return self.user_type == 'admin'

    @property
    def can_post(self):
        return self.authorized_for('user')

    def can_edit(self, user):
        return self.id == user.id or user.is_admin

sarabande/users/__init__.py
from flask import Blueprint


users = Blueprint('users', __name__, template_folder='templates')

from .views import *

sarabande/users/views.py
from flask import render_template, redirect, flash
from flask_login import current_user, login_user
from sqlalchemy.exc import IntegrityError

from sarabande import db, login_manager, safe_return_to
from sarabande.users import users
from sarabande.sessions import login_required
from sarabande.models import User
from .form import UserForm


@users.route('/account/new', methods=['GET'])
def new():
    form = UserForm()
    return render_template('users_new.html', form=form)


@users.route('/account', methods=['POST'])
def create():
    form = UserForm()
    if form.validate(current_user):
        user = form.to_user()
        try:
            db.session.add(user)
            db.session.commit()
            if not current_user.is_authenticated:
                login_user(user)
            flash('Account created!', 'success')
            return redirect(safe_return_to())
        except IntegrityError:
            db.session.rollback()
            form.username.errors.append('This name has been taken.')
    return render_template('users_new.html', form=form)


@users.route('/account/edit', methods=['GET'])
@login_required()
def edit_self():
    form = UserForm(obj=current_user)
    return render_template('users_edit.html', form=form, user=current_user)


@users.route('/account/<int:id>/edit', methods=['GET'])
@login_required('admin')
def edit(id):
    user = User.query.get_or_404(id)
    form = UserForm(obj=user)
    return render_template('users_edit.html', form=form, user=user)


@users.route('/account/<int:id>', methods=['POST'])
@login_required()
def update(id):
    user = User.query.get_or_404(id)
    if not user.can_edit(current_user):
        return login_manager.unauthorized()
    form = UserForm()
    if form.validate(current_user, user):
        form.update_user(user)
        try:
            db.session.add(user)
            db.session.commit()
            flash('Account updated!', 'success')
            return redirect('/')
        except IntegrityError:
            db.session.rollback()
            form.username.errors.append('This name has been taken.')
    return render_template('users_edit.html', form=form, user=user)


@users.route('/account/<int:id>/destroy', methods=['POST'])
@login_required()
def destroy(id):
    user = User.query.get_or_404(id)
    if not user.can_edit(current_user):
        return login_manager.unauthorized()
    db.session.delete(user)
    db.session.commit()
    flash('Account deleted', 'success')
    return redirect('/')

sarabande/templates/users/edit.html
{% from "_form.html" import render_field %}
{% extends "layout.html" %}
{% block title %}Edit {{ form.username.data }}{% endblock %}
{% block body %}
<h1>Edit {{ form.username.data }}</h1>

<form method="POST" action="{{ url_for('users.update', id=user.id) }}">
  {{ form.csrf_token }}
  {{ render_field(form.username, autofocus=True) }}
  {{ render_field(form.password) }}
  {% if current_user.is_authenticated and current_user.is_admin %}
    {{ render_field(form.user_type) }}
  {% endif %}
  <button class="button button--primary">Submit</button>
</form>
{% endblock %}

sarabande/templates/users/new.html
{% from "_form.html" import render_field %}
{% extends "layout.html" %}
{% block title %}New Account{% endblock %}
{% block body %}
<h1>Create Account</h1>

<form method="POST" action="{{ url_for('users.create') }}">
  {{ form.csrf_token }}
  {{ render_field(form.username, autofocus=True) }}
  {{ render_field(form.password) }}
  {% if current_user.is_authenticated and current_user.is_admin %}
    {{ render_field(form.user_type) }}
  {% endif %}
  <button class="button button--primary">Submit</button>
</form>
{% endblock %}