sarabande/models/post.py
from datetime import datetime

from sqlalchemy.ext.hybrid import hybrid_property

from sarabande import db
from .cms_model import CMSModel
from .posts_tags import posts_tags


class Post(db.Model, CMSModel):
    __tablename__ = 'posts'

    title = db.Column(db.String, nullable=False)
    slug = db.Column(db.String, unique=True, nullable=False, index=True)
    body = db.Column(db.Text, nullable=False)
    published_at = db.Column(db.DateTime, index=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False,
                        index=True)
    user = db.relationship('User', backref=db.backref('posts', lazy=True))
    tags = db.relationship('Tag', secondary=posts_tags,
                           back_populates='posts', lazy=True)

    def __init__(self, *args, **kwargs):
        if not kwargs.get('slug'):
            kwargs['slug'] = self.slugify(kwargs.get('title'))
        super(Post, self).__init__(*args, **kwargs)

    def __repr__(self):
        return '<Post {title}>'.format(title=self.title)

    @property
    def author_name(self):
        return self.user.username

    @property
    def tag_names(self):
        return ', '.join([tag.name for tag in self.tags])

    @hybrid_property
    def published(self):
        return self.published_at and self.published_at <= datetime.utcnow()

    def can_edit(self, user):
        if not user.is_authenticated:
            return False
        return user.is_admin or self.user_id == user.id

sarabande/posts/__init__.py
from flask import Blueprint


posts = Blueprint('posts', __name__, template_folder='templates')

from .views import *

sarabande/posts/views.py
from flask import render_template, redirect, url_for, flash, abort
from flask_login import current_user
from sqlalchemy.exc import IntegrityError

from sarabande import db, login_manager
from sarabande.posts import posts
from sarabande.models import Post, Comment
from sarabande.sessions import login_required
from .form import PostForm, CommentForm


@posts.route('/posts', methods=['GET'])
def index():
    pagination = Post.query.filter(Post.published).order_by(
        Post.published_at.desc()).paginate(per_page=5)
    return render_template('posts_index.html', posts=pagination.items,
                           pagination=pagination)


@posts.route('/posts/<slug>', methods=['GET'])
def show(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    if post.published or post.can_edit(current_user):
        return render_template('posts_show.html', post=post)
    abort(404)


@posts.route('/posts/new', methods=['GET'])
@login_required('user')
def new():
    form = PostForm()
    return render_template('posts_new.html', form=form)


@posts.route('/posts', methods=['POST'])
@login_required('user')
def create():
    form = PostForm()
    if form.validate():
        try:
            post = form.to_post(user=current_user)
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('posts.show', slug=post.slug))
        except IntegrityError:
            db.session.rollback()
            form.slug.errors.append('This slug is taken.')
    return render_template('posts_new.html', form=form)


@posts.route('/posts/<slug>/edit', methods=['GET'])
@login_required('user')
def edit(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    if not post.can_edit(current_user):
        return login_manager.unauthorized()
    form = PostForm(obj=post)
    form.tag_names.data = post.tag_names
    return render_template('posts_edit.html', form=form)


@posts.route('/posts/<slug>', methods=['POST'])
@login_required('user')
def update(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    if not post.can_edit(current_user):
        return login_manager.unauthorized()
    form = PostForm()
    if form.validate():
        try:
            form.update_post(post)
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('posts.show', slug=post.slug))
        except IntegrityError:
            db.session.rollback()
            form.slug.errors.append('This slug is taken.')
    return render_template('posts_edit.html', form=form)


@posts.route('/posts/<slug>/destroy', methods=['POST'])
@login_required('user')
def destroy(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    if not post.can_edit(current_user):
        return login_manager.unauthorized()
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted', 'success')
    return redirect(url_for('admin.posts'))


@posts.route('/posts/<slug>/comments', methods=['GET'])
def comments_index(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    form = PostForm()
    return render_template('comments_index.html', post=post, form=form)


@posts.route('/posts/<slug>/comments', methods=['POST'])
@login_required()
def comments_create(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    form = CommentForm()
    if form.validate():
        comment = form.to_comment(user=current_user, post=post)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('posts.comments_index', slug=slug))
    return render_template('comments_index.html', form=form, post=post)


@posts.route('/comments/<int:id>/destroy', methods=['POST'])
@login_required('user')
def comments_destroy(id):
    comment = Comment.query.get_or_404(id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted', 'success')
    return redirect(url_for('admin.comments'))

sarabande/templates/posts/edit.html
{% from "_form.html" import render_field %}
{% extends "layout.html" %}
{% block title %}Edit {{ form.title.data }}{% endblock %}
{% block body %}
<h1>Edit {{ form.title.data }}</h1>

<form method="POST" action="{{ url_for('posts.update', slug=form.slug.data) }}">
  {{ form.csrf_token }}
  {{ render_field(form.title, autofocus=True) }}
  {{ render_field(form.slug) }}
  {{ render_field(form.body) }}
  <button class="button button--primary">Submit</button>
</form>
{{ asset_tag('admin.js') }}
{% endblock %}

sarabande/templates/posts/index.html
{% extends "layout.html" %}
{% block title %}Posts{% endblock %}
{% block body %}
<h1>Posts</h1>
<ul class="unstyled-list">
{% for post in posts %}
<li class="flex">
  <h3 class="mr-1"><a href="{{ url_for('posts.show', slug=post.slug) }}" class="unstyled-link">{{ post.title }}</a></h3>
  <p>by {{ post.author_name }}</p>
</li>
{% endfor %}
</ul>
{% endblock %}

sarabande/templates/posts/new.html
{% from "_form.html" import render_field %}
{% extends "layout.html" %}
{% block title %}Create Post{% endblock %}
{% block body %}
<h1>Create new post</h1>

<form method="POST" action="{{ url_for('posts.create') }}">
  {{ form.csrf_token }}
  {{ render_field(form.title, autofocus=True) }}
  {{ render_field(form.slug) }}
  {{ render_field(form.body) }}
  <button class="button button--primary">Submit</button>
</form>
{{ asset_tag('admin.js') }}
{% endblock %}

sarabande/templates/posts/show.html
{% extends "layout.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block body %}
<h1>{{ post.title }}</h1>
<p>by {{ post.author_name }}</p>
{{ post.html_body }}
{% endblock %}